# this file defines behavior for the 'monitored_server' class of nodes

- name: install gmond
  action: yum pkg=ganglia-gmond state=installed

- name: configure gmond
  action: template src=templates/etc/ganglia/gmond.conf dest=/etc/ganglia/gmond.conf owner=root group=root
  notify:
      - restart gmond

- name: ensure ganglia is running
  action: service name=gmond state=running

